name: kaccha_pakka_khata
description: A minimal Flutter project skeleton for Kaccha Pakka Khata.
publish_to: 'none'
version: 1.2.3+10
# Here the first 1 is for Major Version, in this case we add a big change.
# the second 1 is for Minor Version, in this case we add a new feature.
# the third 0 is for Patch Version, in this case we fix a bug.
# the fourth 0 is for Build Number, in this case we do a small change.
# Version of the app
# Never Change it after Publishing, It will be treated as a unique identifier for your app.
# But when you make a change in the app, you need to increment the version number.
# And when you add a new feature or make a bug fix or any other change, you need to increment the version number.

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.1.1
  pdf: ^3.11.0
  printing: ^5.12.0
  google_fonts: ^8.0.1
  intl: ^0.20.2
  flutter_slidable: ^4.0.3
  supabase_flutter: ^2.12.0
  flutter_dotenv: ^6.0.0
  google_sign_in: ^7.2.0
  share_plus: ^12.0.1
  universal_html: ^2.2.4
  onesignal_flutter: ^5.4.1
  purchases_flutter: ^10.0.1
  purchases_ui_flutter: ^10.0.1
  image_picker: ^1.2.2
  url_launcher: ^6.3.2
  google_mobile_ads: ^9.0.0
  http: ^1.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.5.0
  flutter_launcher_icons: "^0.14.4"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#ffffff"
    theme_color: "#FF1616"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - shorebird.yaml
